"""add order tables

Revision ID: 2fe91270fdaa
Revises: 75f4f42cb1c9
Create Date: 2025-12-14 02:42:28.882541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2fe91270fdaa'
down_revision: Union[str, Sequence[str], None] = '75f4f42cb1c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_index('ix_user_email_lower', 'user', [sa.literal_column('(lower(email))')], unique=True)
    op.drop_index(op.f('ix_user_email_lower'), table_name='user')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_email_lower', table_name='user')
    op.create_index(op.f('ix_user_email_lower'), 'user', [], unique=True)



    # ### end Alembic commands ###
