"""create order tables

Revision ID: 8f5541e678d9
Revises: 2fe91270fdaa
Create Date: 2025-12-14 03:14:33.304107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8f5541e678d9'
down_revision: Union[str, Sequence[str], None] = '2fe91270fdaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('order_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('order_item',
    sa.Column('order_item_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('book_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.book_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['order.order_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('order_item_id')
    )
    op.alter_column('favorite', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.drop_constraint(op.f('favorite_ibfk_2'), 'favorite', type_='foreignkey')
    op.drop_constraint(op.f('favorite_ibfk_1'), 'favorite', type_='foreignkey')
    op.create_foreign_key(None, 'favorite', 'user', ['user_id'], ['user_id'])
    op.create_foreign_key(None, 'favorite', 'book', ['book_id'], ['book_id'])
    op.drop_index(op.f('ix_user_email_lower'), table_name='user')
    op.create_index('ix_user_email_lower', 'user', [sa.literal_column('(lower(email))')], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_email_lower', table_name='user')
    op.create_index(op.f('ix_user_email_lower'), 'user', [], unique=True)
    op.drop_constraint(None, 'favorite', type_='foreignkey')
    op.drop_constraint(None, 'favorite', type_='foreignkey')
    op.create_foreign_key(op.f('favorite_ibfk_1'), 'favorite', 'book', ['book_id'], ['book_id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_foreign_key(op.f('favorite_ibfk_2'), 'favorite', 'user', ['user_id'], ['user_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('favorite', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.drop_table('order_item')
    op.drop_table('order')
    # ### end Alembic commands ###
