"""create authors and books tables v2

Revision ID: d0a199b80a6d
Revises: d8f65ab332af
Create Date: 2025-12-13 20:34:06.279121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0a199b80a6d'
down_revision: Union[str, Sequence[str], None] = 'd8f65ab332af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('author_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('profile', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('author_id')
    )
    op.create_table('book',
    sa.Column('book_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('isbn', sa.String(length=20), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('published_date', sa.Date(), nullable=True),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['authors.author_id'], ),
    sa.PrimaryKeyConstraint('book_id'),
    sa.UniqueConstraint('isbn')
    )
    op.drop_index(op.f('ix_user_email_lower'), table_name='user')
    op.create_index('ix_user_email_lower', 'user', [sa.literal_column('(lower(email))')], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_email_lower', table_name='user')
    op.create_index(op.f('ix_user_email_lower'), 'user', [], unique=True)
    op.drop_table('book')
    op.drop_table('authors')
    # ### end Alembic commands ###
