"""create authors and books tables

Revision ID: d8f65ab332af
Revises: cd4527e01c51
Create Date: 2025-12-13 20:21:08.747110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8f65ab332af'
down_revision: Union[str, Sequence[str], None] = 'cd4527e01c51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_email_lower', 'user', [sa.literal_column('(lower(email))')], unique=True)
    op.drop_index(op.f('idx_user_token_user_id'), table_name='user_token')
    op.create_index('ix_user_token_user_id', 'user_token', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_token_user_id', table_name='user_token')
    op.create_index(op.f('idx_user_token_user_id'), 'user_token', ['user_id'], unique=False)
    op.drop_index('ix_user_email_lower', table_name='user')
    # ### end Alembic commands ###
