"""add favorite table

Revision ID: e2e7e483d167
Revises: d0a199b80a6d
Create Date: 2025-12-14 01:05:52.479607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2e7e483d167'
down_revision: Union[str, Sequence[str], None] = 'd0a199b80a6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite',
    sa.Column('favorite_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('book_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.book_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('favorite_id'),
    sa.UniqueConstraint('user_id', 'book_id', name='uq_favorite_user_book')
    )
    op.create_index('ix_favorite_user_created_at', 'favorite', ['user_id', 'created_at'], unique=False)
    op.drop_index(op.f('ix_user_email_lower'), table_name='user')
    op.create_index('ix_user_email_lower', 'user', [sa.literal_column('(lower(email))')], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_email_lower', table_name='user')
    op.create_index(op.f('ix_user_email_lower'), 'user', [], unique=True)
    op.drop_index('ix_favorite_user_created_at', table_name='favorite')
    op.drop_table('favorite')
    # ### end Alembic commands ###
